export type MockCourse = {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: string;
  categorySlug: string;
  level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  price: number;
  salePrice?: number;
  rating: number;
  reviewCount: number;
  totalLessons: number;
  totalDuration: string;
  badge?: string;
  gradient: string;
  featured: boolean;
  whatYouLearn: string[];
  requirements: string[];
};

export const mockCourses: MockCourse[] = [
  {
    id: "1",
    title: "React & Next.js từ 0 đến Pro",
    slug: "react-nextjs-tu-0-den-pro",
    description: "Khóa học toàn diện về React và Next.js 14, từ cơ bản đến nâng cao. Bạn sẽ xây dựng các dự án thực tế, hiểu sâu về Server Components, App Router, và deploy lên production.",
    category: "Lập trình Web",
    categorySlug: "lap-trinh-web",
    level: "BEGINNER",
    price: 2599000,
    salePrice: 1299000,
    rating: 4.9,
    reviewCount: 3240,
    totalLessons: 42,
    totalDuration: "18 giờ",
    badge: "Bán chạy",
    gradient: "from-blue-600 to-teal-500",
    featured: true,
    whatYouLearn: ["React Hooks & Context API", "Next.js App Router", "Server & Client Components", "Prisma + PostgreSQL", "Deploy lên Vercel"],
    requirements: ["Biết HTML/CSS cơ bản", "JavaScript cơ bản"],
  },
  {
    id: "2",
    title: "UI/UX Design Masterclass với Figma",
    slug: "uiux-design-masterclass-figma",
    description: "Học thiết kế UI/UX chuyên nghiệp với Figma. Từ wireframe đến prototype hoàn chỉnh, design system, và handoff cho developer.",
    category: "Thiết kế UI/UX",
    categorySlug: "thiet-ke",
    level: "BEGINNER",
    price: 1499000,
    salePrice: 799000,
    rating: 4.8,
    reviewCount: 2100,
    totalLessons: 38,
    totalDuration: "22 giờ",
    badge: "Mới",
    gradient: "from-purple-600 to-pink-500",
    featured: true,
    whatYouLearn: ["Nguyên lý thiết kế UI/UX", "Figma từ cơ bản đến nâng cao", "Design System", "Prototype tương tác", "Handoff cho dev"],
    requirements: ["Không cần kinh nghiệm", "Máy tính có cài Figma"],
  },
  {
    id: "3",
    title: "Python & Data Science cho người mới",
    slug: "python-data-science-nguoi-moi",
    description: "Khởi đầu hành trình Data Science với Python. Pandas, NumPy, Matplotlib, Scikit-learn và các dự án thực tế từ dữ liệu thật.",
    category: "Data Science",
    categorySlug: "data-science",
    level: "BEGINNER",
    price: 1399000,
    rating: 4.9,
    reviewCount: 1850,
    totalLessons: 55,
    totalDuration: "25 giờ",
    badge: "Nổi bật",
    gradient: "from-green-600 to-teal-500",
    featured: true,
    whatYouLearn: ["Python cơ bản đến nâng cao", "Pandas & NumPy", "Data Visualization", "Machine Learning cơ bản", "Dự án thực tế"],
    requirements: ["Không cần biết lập trình", "Tinh thần ham học hỏi"],
  },
  {
    id: "4",
    title: "Digital Marketing toàn diện 2025",
    slug: "digital-marketing-toan-dien-2025",
    description: "Chiến lược digital marketing từ SEO, Facebook Ads, Google Ads đến Content Marketing và Email Marketing. Học từ chuyên gia với 10 năm kinh nghiệm.",
    category: "Marketing",
    categorySlug: "marketing",
    level: "BEGINNER",
    price: 999000,
    salePrice: 499000,
    rating: 4.7,
    reviewCount: 1620,
    totalLessons: 30,
    totalDuration: "15 giờ",
    badge: "Bán chạy",
    gradient: "from-orange-500 to-red-500",
    featured: false,
    whatYouLearn: ["SEO On-page & Off-page", "Facebook & Google Ads", "Content Marketing", "Email Marketing", "Analytics & Reporting"],
    requirements: ["Không yêu cầu kinh nghiệm", "Laptop kết nối internet"],
  },
  {
    id: "5",
    title: "Flutter & Dart: Lập trình Mobile",
    slug: "flutter-dart-lap-trinh-mobile",
    description: "Xây dựng ứng dụng mobile iOS & Android với Flutter. State management, Firebase, REST API và publish lên App Store.",
    category: "Mobile App",
    categorySlug: "mobile-app",
    level: "INTERMEDIATE",
    price: 1799000,
    salePrice: 1099000,
    rating: 4.8,
    reviewCount: 980,
    totalLessons: 48,
    totalDuration: "20 giờ",
    gradient: "from-sky-500 to-blue-600",
    featured: false,
    whatYouLearn: ["Dart cơ bản đến nâng cao", "Flutter Widgets", "State Management (Riverpod)", "Firebase Integration", "Publish App"],
    requirements: ["Biết lập trình OOP cơ bản"],
  },
  {
    id: "6",
    title: "Machine Learning với Python",
    slug: "machine-learning-python",
    description: "Học Machine Learning từ lý thuyết đến thực hành. Linear Regression, Random Forest, Neural Networks và deploy model production.",
    category: "AI & Machine Learning",
    categorySlug: "ai-ml",
    level: "INTERMEDIATE",
    price: 2199000,
    salePrice: 1499000,
    rating: 4.9,
    reviewCount: 750,
    totalLessons: 60,
    totalDuration: "30 giờ",
    badge: "Chuyên sâu",
    gradient: "from-violet-600 to-purple-700",
    featured: true,
    whatYouLearn: ["Toán học cho ML", "Scikit-learn", "Deep Learning cơ bản", "Model Deployment", "MLOps basics"],
    requirements: ["Python cơ bản", "Toán THPT"],
  },
  {
    id: "7",
    title: "Node.js & Express: Backend Development",
    slug: "nodejs-express-backend",
    description: "Xây dựng REST API chuyên nghiệp với Node.js và Express. Authentication, Database, Testing và deployment.",
    category: "Lập trình Web",
    categorySlug: "lap-trinh-web",
    level: "INTERMEDIATE",
    price: 1599000,
    salePrice: 899000,
    rating: 4.7,
    reviewCount: 1340,
    totalLessons: 35,
    totalDuration: "16 giờ",
    gradient: "from-teal-600 to-green-600",
    featured: false,
    whatYouLearn: ["Node.js & Express", "REST API Design", "JWT Authentication", "MongoDB & Mongoose", "Testing với Jest"],
    requirements: ["JavaScript cơ bản", "Hiểu về HTTP"],
  },
  {
    id: "8",
    title: "Kinh doanh Online từ A đến Z",
    slug: "kinh-doanh-online-a-z",
    description: "Xây dựng và vận hành kinh doanh online thành công. Từ chọn ngành hàng, xây kênh bán, quản lý vận hành đến scale up.",
    category: "Kinh doanh",
    categorySlug: "kinh-doanh",
    level: "BEGINNER",
    price: 799000,
    salePrice: 399000,
    rating: 4.6,
    reviewCount: 2300,
    totalLessons: 28,
    totalDuration: "12 giờ",
    gradient: "from-amber-500 to-orange-500",
    featured: false,
    whatYouLearn: ["Chọn ngành hàng phù hợp", "Xây dựng thương hiệu cá nhân", "Bán hàng đa kênh", "Quản lý dòng tiền", "Scale business"],
    requirements: ["Không cần kinh nghiệm"],
  },
  {
    id: "9",
    title: "TypeScript Nâng Cao",
    slug: "typescript-nang-cao",
    description: "Thành thạo TypeScript từ Generic, Utility Types đến advanced patterns. Áp dụng vào dự án React và Node.js thực tế.",
    category: "Lập trình Web",
    categorySlug: "lap-trinh-web",
    level: "ADVANCED",
    price: 1299000,
    rating: 4.8,
    reviewCount: 620,
    totalLessons: 32,
    totalDuration: "14 giờ",
    gradient: "from-blue-700 to-indigo-700",
    featured: false,
    whatYouLearn: ["Type System nâng cao", "Generic & Utility Types", "Decorators", "Module System", "Best Practices"],
    requirements: ["JavaScript thành thạo", "TypeScript cơ bản"],
  },
  {
    id: "10",
    title: "Tiếng Anh giao tiếp cho người đi làm",
    slug: "tieng-anh-giao-tiep-di-lam",
    description: "Tiếng Anh thực chiến cho môi trường công sở. Email, meeting, presentation và networking bằng tiếng Anh tự tin.",
    category: "Ngoại ngữ",
    categorySlug: "ngoai-ngu",
    level: "BEGINNER",
    price: 699000,
    salePrice: 0,
    rating: 4.7,
    reviewCount: 3100,
    totalLessons: 45,
    totalDuration: "20 giờ",
    badge: "Miễn phí",
    gradient: "from-rose-500 to-pink-600",
    featured: false,
    whatYouLearn: ["Business Email", "Meeting & Presentation", "Networking", "IELTS cơ bản", "Phát âm chuẩn"],
    requirements: ["Tiếng Anh A2 trở lên"],
  },
  {
    id: "11",
    title: "DevOps & Docker cho Developer",
    slug: "devops-docker-developer",
    description: "Hiểu và thực hành DevOps: Docker, CI/CD, Kubernetes cơ bản. Tự động hóa deploy và monitor ứng dụng production.",
    category: "Lập trình Web",
    categorySlug: "lap-trinh-web",
    level: "INTERMEDIATE",
    price: 1899000,
    salePrice: 1199000,
    rating: 4.8,
    reviewCount: 890,
    totalLessons: 40,
    totalDuration: "18 giờ",
    gradient: "from-slate-600 to-gray-700",
    featured: false,
    whatYouLearn: ["Docker & Docker Compose", "CI/CD với GitHub Actions", "Kubernetes cơ bản", "Monitoring & Logging", "Cloud Deployment"],
    requirements: ["Biết Linux cơ bản", "Có kinh nghiệm dev"],
  },
  {
    id: "12",
    title: "Canva & Thiết kế đồ họa cơ bản",
    slug: "canva-thiet-ke-do-hoa-co-ban",
    description: "Thiết kế đồ họa chuyên nghiệp với Canva. Poster, banner, social media content, presentation đẹp mắt không cần biết thiết kế.",
    category: "Thiết kế UI/UX",
    categorySlug: "thiet-ke",
    level: "BEGINNER",
    price: 0,
    rating: 4.5,
    reviewCount: 4200,
    totalLessons: 20,
    totalDuration: "8 giờ",
    badge: "Miễn phí",
    gradient: "from-fuchsia-500 to-purple-600",
    featured: false,
    whatYouLearn: ["Nguyên tắc thiết kế cơ bản", "Canva Pro", "Social Media Design", "Infographic", "Brand Identity"],
    requirements: ["Không cần biết thiết kế"],
  },
];

export const categories = [
  { name: "Lập trình Web", slug: "lap-trinh-web", icon: "💻" },
  { name: "Thiết kế UI/UX", slug: "thiet-ke", icon: "🎨" },
  { name: "Marketing", slug: "marketing", icon: "📣" },
  { name: "Data Science", slug: "data-science", icon: "📊" },
  { name: "Mobile App", slug: "mobile-app", icon: "📱" },
  { name: "AI & Machine Learning", slug: "ai-ml", icon: "🤖" },
  { name: "Kinh doanh", slug: "kinh-doanh", icon: "💼" },
  { name: "Ngoại ngữ", slug: "ngoai-ngu", icon: "🌐" },
];

export const levelLabel: Record<string, string> = {
  BEGINNER: "Cơ bản",
  INTERMEDIATE: "Trung cấp",
  ADVANCED: "Nâng cao",
};

export const formatPrice = (price: number) =>
  price === 0 ? "Miễn phí" : price.toLocaleString("vi-VN") + "₫";
